Controllers/InquiryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPractice.Models;
namespace WebPractice.Controllers
{
    public class InquiryController : Controller
    {
        PracticeDBEF dc = new PracticeDBEF();
        // GET: Inquiry
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            tblInquiry Inq = new tblInquiry();
            Inq.FirstName = form["txtFname"];
            Inq.LastName = form["txtLname"];
            Inq.ContactNo = form["txtContactNo"];
            Inq.Email = form["txtEmail"];
            Inq.Subject = form["txtSubject"];
            Inq.Query = form["txtQuery"];
            Inq.CreatedOn = DateTime.Now;
            dc.tblInquiries.Add(Inq);
            dc.SaveChanges();
            return RedirectToAction("Index","Home");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="@Url.Action("index","Home")">MVC Practice</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("index","Home")">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        User
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="@Url.Action("index","Home")">Login</a>
                        <a class="dropdown-item" href="@Url.Action("UserProfile","Home")"> User Profile </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("UserList","Home")">User List</a>
                        <a class="dropdown-item" href="@Url.Action("Create","Home")">Add New User</a>
                        
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Product
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="@Url.Action("index","ClientProduct")">Add New Product</a>
                        <a class="dropdown-item" href="@Url.Action("ViewProdList","ClientProduct")"> View Product </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("UpdateProd","ClientProduct")"> Update Product</a>
                        <a class="dropdown-item" href="@Url.Action("ViewClient","ClientProduct")">Client View</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index","Inquiry")">Contact Us</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="@Url.Action("search","Home")" method="post">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <h1 style="margin-top:50px"></h1>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            <br />
            <a href="@Url.Action("Index","Admin/Admin")"> Admin Panel </a>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>