Controllers/ClientProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPractice.Models;
namespace WebPractice.Controllers
{
    public class ClientProductController : Controller
    { 
        // GET: ClientProduct
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(tblProduct prod)
        {
            // Add Fields which is not taken from Form
            prod.CreatedOn = DateTime.Now;
            prod.UserID = 1;
            prod.CatID = 1;

            // Save to DB
            PracticeDBEF dc = new PracticeDBEF();
            dc.tblProducts.Add(prod);
            dc.SaveChanges();
            return View();
        }
        public ActionResult ViewProd()
        {
            PracticeDBEF dc = new PracticeDBEF();
            //var Prods = dc.tblProducts.ToList();
            //return View(Prods);
            var Prods = from ob in dc.tblProducts
                        join ob2 in dc.tblUsers
                        on ob.UserID equals ob2.UserID
                        select new UserProducts
                        {
                            user = ob2,
                            product = ob
                        };

            return View(Prods);
        }
    }
}

Views/ClientProduct/Index.cshtml
@model WebPractice.Models.tblProduct
@{
    ViewBag.Title = "Products";
}

<h2 class="card-title">Add New Product</h2>
<div class="btn btn-dark" style="margin:0px 0px 20px 0px">
    @Html.ActionLink("View Your Products", "ViewProd", "ClientProduct")
</div>
@* HTML.<> Executes the code and
    URL.<> Return the URL of given Action Link *@
<div class="col-lg-10">
    @using (Html.BeginForm("Index", "ClientProduct", FormMethod.Post))
    {
        @Html.EditorFor(model => model.ProdName, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Product Name" } })
        <br />
        @*@Html.DropDownListFor(ViewData.Cat, new { htmlAttributes = new { @class = "form-control", placeholder = "Select Category" } })*@
        <br />
        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Product Name" } })
        <br />
        @Html.EditorFor(model => model.ProdDesc, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Product Name" } })
        <br />
        <input type="submit" class="btn btn-success" />
    }
</div>

Views/ClientProduct/ViewProd.cshtml
@model IEnumerable<WebPractice.Models.UserProducts>


@{
    ViewBag.Title = "ViewProd";
}

<h2>All Products</h2>

<p>
    @Html.ActionLink("Create New", "Index")
</p>
<table class="table">
    <tr>
        <th>
            Product Name
            @*@Html.DisplayNameFor(model => model.ProdName)*@
        </th>
        <th>
            CategoryID
            @*@Html.DisplayNameFor(model => model.CatID)*@
        </th>
        <th>
            Description
            @*@Html.DisplayNameFor(model => model.ProdDesc)*@
        </th>
        <th>
            Price
            @*@Html.DisplayNameFor(model => model.Price)*@
        </th>
        <th>
            UserName
            @*@Html.DisplayNameFor(model => model.UserID)*@
        </th>
        <th>
            CreatedOn
            @*@Html.DisplayNameFor(model => model.CreatedOn)*@
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @item.product.ProdName
            @*@Html.DisplayFor(modelItem => item.ProdName)*@
        </td>
        <td>
            @item.product.CatID
            @*@Html.DisplayFor(modelItem => item.CatID)*@
        </td>
        <td>
            @item.product.ProdDesc
            @*@Html.DisplayFor(modelItem => item.ProdDesc)*@
        </td>
        <td>
            @item.product.Price
            @*@Html.DisplayFor(modelItem => item.Price)*@
        </td>
        <td>
            @item.user.Name
            @*@Html.DisplayFor(modelItem => item.UserID)*@
        </td>
        <td>
            @item.product.CreatedOn
            @*@Html.DisplayFor(modelItem => item.CreatedOn)*@
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.product.ProdID }) |
            @Html.ActionLink("Details", "Details", new { id=item.product.ProdID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.product.ProdID })
        </td>
    </tr>
}

</table>